### ISSUE TITLE
Error parsing rsponse body

### ISSUE THREAD

**Issue by Pitillo** [kaklakariada/fritzbox-java-api#7]
I get the following error, when I try to get the deviceList. There seems to be a problem at parsing the returned xml File.
Error:
```
Exception in thread "main" com.github.kaklakariada.fritzbox.mapping.DeserializerException: Error parsing response body '<devicelist version="1"><device identifier="11795 0264704" id="16" functionbitmask="320" fwversion="04.36" manufacturer="AVM" productname="FRITZ!DECT 300"><present>1</present><name>Ärzte 1 DECT300</name><temperature><celsius>165</celsius><offset>0</offset></temperature><hkr><tist>33</tist><tsoll>33</tsoll><absenk>33</absenk><komfort>46</komfort><lock>0</lock><devicelock>1</devicelock><errorcode>0</errorcode><batterylow>0</batterylow><nextchange><endperiod>1516332600</endperiod><tchange>46</tchange></nextchange></hkr></device><device identifier="11959 0567408" id="17" functionbitmask="320" fwversion="04.36" manufacturer="AVM" productname="FRITZ!DECT 300"><present>1</present><name>Ärzte 2 DECT300</name><temperature><celsius>165</celsius><offset>0</offset></temperature><hkr><tist>33</tist><tsoll>33</tsoll><absenk>33</absenk><komfort>46</komfort><lock>0</lock><devicelock>1</devicelock><errorcode>0</errorcode><batterylow>0</batterylow><nextchange><endperiod>1516332600</endperiod><tchange>46</tchange></nextchange></hkr></device><device identifier="11795 0239200" id="20000" functionbitmask="320" fwversion="04.36" manufacturer="AVM" productname="FRITZ!DECT 300"><present>1</present><name>Küche DECT300</name><temperature><celsius>225</celsius><offset>0</offset></temperature><hkr><tist>45</tist><tsoll>44</tsoll><absenk>33</absenk><komfort>44</komfort><lock>0</lock><devicelock>1</devicelock><errorcode>0</errorcode><batterylow>0</batterylow><nextchange><endperiod>1516273200</endperiod><tchange>33</tchange></nextchange></hkr></device><device identifier="11959 0400568" id="20001" functionbitmask="320" fwversion="04.36" manufacturer="AVM" productname="FRITZ!DECT 300"><present>1</present><name>Umkleide DECT300</name><temperature><celsius>190</celsius><offset>0</offset></temperature><hkr><tist>38</tist><tsoll>38</tsoll><absenk>33</absenk><komfort>38</komfort><lock>0</lock><devicelock>1</devicelock><errorcode>0</errorcode><batterylow>0</batterylow><nextchange><endperiod>1516273200</endperiod><tchange>33</tchange></nextchange></hkr></device><device identifier="11959 0541176" id="20002" functionbitmask="320" fwversion="04.36" manufacturer="AVM" productname="FRITZ!DECT 300"><present>1</present><name>WC Küche DECT300</name><temperature><celsius>105</celsius><offset>0</offset></temperature><hkr><tist>21</tist><tsoll>38</tsoll><absenk>33</absenk><komfort>38</komfort><lock>0</lock><devicelock>1</devicelock><errorcode>0</errorcode><batterylow>0</batterylow><nextchange><endperiod>1516273200</endperiod><tchange>33</tchange></nextchange></hkr></device></devicelist>'
	at com.github.kaklakariada.fritzbox.mapping.Deserializer.parse(Deserializer.java:59)
	at com.github.kaklakariada.fritzbox.http.HttpTemplate.parse(HttpTemplate.java:102)
	at com.github.kaklakariada.fritzbox.http.HttpTemplate.get(HttpTemplate.java:82)
	at com.github.kaklakariada.fritzbox.http.HttpTemplate.get(HttpTemplate.java:71)
	at com.github.kaklakariada.fritzbox.FritzBoxSession.getAutenticated(FritzBoxSession.java:90)
	at com.github.kaklakariada.fritzbox.HomeAutomation.executeCommand(HomeAutomation.java:56)
	at com.github.kaklakariada.fritzbox.HomeAutomation.getDeviceListInfos(HomeAutomation.java:48)
Caused by: org.simpleframework.xml.core.ElementException: Element 'hkr' does not have a match in class com.github.kaklakariada.fritzbox.model.homeautomation.Device at line 1
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:527)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:190)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:167)
	at org.simpleframework.xml.core.CompositeInlineList.read(CompositeInlineList.java:124)
	at org.simpleframework.xml.core.Composite.readVariable(Composite.java:623)
	at org.simpleframework.xml.core.Composite.readInstance(Composite.java:573)
	at org.simpleframework.xml.core.Composite.readUnion(Composite.java:549)
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:532)
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445)
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59)
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383)
	at org.simpleframework.xml.core.Composite.read(Composite.java:201)
	at org.simpleframework.xml.core.Composite.read(Composite.java:148)
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92)
	at org.simpleframework.xml.core.Persister.read(Persister.java:625)
	at org.simpleframework.xml.core.Persister.read(Persister.java:606)
	at org.simpleframework.xml.core.Persister.read(Persister.java:584)
	at org.simpleframework.xml.core.Persister.read(Persister.java:562)
	at org.simpleframework.xml.core.Persister.read(Persister.java:499)
	at org.simpleframework.xml.core.Persister.read(Persister.java:408)
	at com.github.kaklakariada.fritzbox.mapping.Deserializer.parse(Deserializer.java:55)
```

The error is caused by the following code:
```java
HomeAutomation home = HomeAutomation.connect("<ip>", "<username>", "<password>");
DeviceList lst = home.getDeviceListInfos();
for(Device dev:lst.getDevices())
{
    log.info(dev.toString());
}
```

I´m using FRITZ!OS version 06.83.
I hope you can fix the parsing error with the given information.

**Comment by Pitillo** [comment]
Ok, I´ve fixed the problem my self. Some changes and some new classes were needed. 
Device.java:
```Java
/**
 * A Java API for managing FritzBox HomeAutomation
 * Copyright (C) 2017 Christoph Pirkl <christoph at users.sourceforge.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.kaklakariada.fritzbox.model.homeautomation;

import org.simpleframework.xml.Attribute;
import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

@Root(name = "device")
public class Device {

    @Attribute(name = "identifier", required = true)
    private String identifier;
    @Attribute(name = "id")
    private String id;
    @Attribute(name = "functionbitmask")
    private int functionBitmask;
    @Attribute(name = "fwversion")
    private String firmwareVersion;
    @Attribute(name = "manufacturer")
    private String manufacturer;

    @Attribute(name = "productname")
    private String productName;

    @Element(name = "present")
    private String present;
    @Element(name = "name")
    private String name;

    @Element(name = "switch", required = false)
    private SwitchState switchState;
    @Element(name = "powermeter", required = false)
    private PowerMeter powerMeter;
    @Element(name = "temperature", required = false)
    private Temperature temperature;
	@Element(name = "hkr", required = false)
	private HKR hkr;

    public String getIdentifier() {
        return identifier;
    }

    public String getId() {
        return id;
    }

    public int getFunctionBitmask() {
        return functionBitmask;
    }

    public String getFirmwareVersion() {
        return firmwareVersion;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public String getProductName() {
        return productName;
    }

    public boolean isPresent() {
        return "1".equals(present);
    }

    public String getName() {
        return name;
    }

    public SwitchState getSwitchState() {
        return switchState.isNull() ? null : switchState;
    }

    public PowerMeter getPowerMeter() {
        return powerMeter;
    }

    public Temperature getTemperature() {
        return temperature;
    }
	
	public HKR getHKR()
	{
		return hkr;
	}

    @Override
    public String toString() {
        return "Device [identifier=" + identifier + ", id=" + id + ", functionBitmask=" + functionBitmask
                + ", firmwareVersion=" + firmwareVersion + ", manufacturer=" + manufacturer + ", productName="
                + productName + ", present=" + present + ", name=" + name + ", switchState=" + switchState
                + ", powerMeter=" + powerMeter + ", temperature=" + temperature + ", hkr=" + hkr + "]";
    }
}
```

HKR.java:
```Java
/**
 * A Java API for managing FritzBox HomeAutomation
 * Copyright (C) 2017 Christoph Pirkl <christoph at users.sourceforge.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.kaklakariada.fritzbox.model.homeautomation;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

@Root(name = "hkr")
public class HKR
{

	@Element(name = "tist", required = false)
	private int tist;

	@Element(name = "tsoll", required = false)
	private int tsoll;

	@Element(name = "absenk", required = false)
	private int tabsenk;

	@Element(name = "komfort", required = false)
	private int komfort;

	@Element(name = "lock", required = false)
	private int lock;

	@Element(name = "devicelock", required = false)
	private int devicelock;

	@Element(name = "errorcode", required = false)
	private int errorcode;

	@Element(name = "batterylow", required = false)
	private int batterylow;

	@Element(name = "nextchange", required = false)
	private NextChange nextChange;

	public int getTist()
	{
	    return tist;
	}

	public void setTist(int tist)
	{
	    this.tist = tist;
	}

	public int getTsoll()
	{
	    return tsoll;
	}

	public void setTsoll(int tsoll)
	{
	    this.tsoll = tsoll;
	}

	public int getTabsenk()
	{
	    return tabsenk;
	}

	public void setTabsenk(int tabsenk)
	{
	    this.tabsenk = tabsenk;
	}

	public int getKomfort()
	{
	    return komfort;
	}

	public void setKomfort(int komfort)
	{
	    this.komfort = komfort;
	}

	public int getLock()
	{
	    return lock;
	}

	public void setLock(int lock)
	{
	    this.lock = lock;
	}

	public int getDevicelock()
	{
	    return devicelock;
	}

	public void setDevicelock(int devicelock)
	{
	    this.devicelock = devicelock;
	}

	public int getErrorcode()
	{
	    return errorcode;
	}

	public void setErrorcode(int errorcode)
	{
	    this.errorcode = errorcode;
	}

	public int getBatterylow()
	{
	    return batterylow;
	}

	public void setBatterylow(int batterylow)
	{
	    this.batterylow = batterylow;
	}

	public NextChange getNextChange()
	{
	    return nextChange;
	}

	public void setNextChange(NextChange nextChange)
	{
	    this.nextChange = nextChange;
	}

	@Override
	public String toString()
	{
	    return "HKR[" + "tist=" + tist + ", tsoll=" + tsoll + ", tabsenk=" + tabsenk + ", komfort=" + komfort + ", lock=" + lock + ", devicelock=" + devicelock + ", errorcode=" + errorcode + ", batterylow=" + batterylow + ", nextChange=" + nextChange + ']';
	}
}
```

NextChange.java:
```Java
/**
 * A Java API for managing FritzBox HomeAutomation
 * Copyright (C) 2017 Christoph Pirkl <christoph at users.sourceforge.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.github.kaklakariada.fritzbox.model.homeautomation;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;

@Root(name = "nextchange")
public class NextChange
    {

	@Element(name = "endperiod", required = false)
	private int endperiod;

	@Element(name = "tchange", required = false)
	private int tchange;

	public int getEndperiod()
	{
	    return endperiod;
	}

	public void setEndperiod(int endperiod)
	{
	    this.endperiod = endperiod;
	}

	public int getTchange()
	{
	    return tchange;
	}

	public void setTchange(int tchange)
	{
	    this.tchange = tchange;
	}

	@Override
	public String toString()
	{
	    return "NextChange[" + "endperiod=" + endperiod + ", tchange=" + tchange + ']';
	}

    }
```

Maybe you could add these files to the repository, so everyone can use the libary to read out FRITTZ!DECT 300 Smarthome Devices.

**Comment by kaklakariada** [comment]
@Pitillo Thanks for the classes, I added them to the code.
